#VARIAVEIS
@baseUrl = http://localhost:3333
###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions


###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/2badf340-8379-4df1-a710-cc7e75dc81ba/questions
Content-Type: application/json

{
  "question": "O que é Vue.js e a sua diferença em relação ao Angular?"
}